import { Mic, Video, PlaySquare, FileText, BookOpen, PenTool, Type } from 'lucide-react';
import type { SourceConfigItem, SourceType } from './types';

export const sourceConfig: Record<SourceType, SourceConfigItem> = {
  audio: {
    id: 'audio',
    title: 'Audio Recording',
    description: 'MP3, WAV, M4A lecture recordings',
    icon: Mic,
    acceptedTypes: 'audio/mpeg, audio/wav, audio/mp4',
    maxFileSize: '500MB',
    multiple: false,
    processor: 'audioProcessor',
    tips: [
      'Supported formats: MP3, WAV, M4A',
      'Maximum file size: 500MB',
      'For best results, ensure clear audio with minimal background noise.',
    ],
  },
  video: {
    id: 'video',
    title: 'Video Lecture',
    description: 'MP4, MOV and recorded classes',
    icon: Video,
    acceptedTypes: 'video/mp4, video/quicktime, video/x-msvideo',
    maxFileSize: '2GB',
    multiple: false,
    processor: 'videoProcessor',
    tips: [
      'Supported formats: MP4, MOV, AVI',
      'Maximum file size: 2GB',
      'Audio will be extracted automatically from your video.',
    ],
  },
  youtube: {
    id: 'youtube',
    title: 'YouTube Video',
    description: 'Paste any public YouTube lecture link',
    icon: PlaySquare,
    acceptedTypes: 'url',
    maxFileSize: 'N/A',
    multiple: false,
    processor: 'youtubeProcessor',
    tips: [
      'Only public or unlisted YouTube videos are supported.',
      'Playlists are not supported yet.',
      'We will automatically fetch the transcript for processing.',
    ],
  },
  pdf: {
    id: 'pdf',
    title: 'PDF Slides',
    description: 'Lecture slides and digital textbooks',
    icon: FileText,
    acceptedTypes: 'application/pdf',
    maxFileSize: '100MB',
    multiple: false,
    processor: 'pdfProcessor',
    tips: [
      'Supported format: PDF',
      'Maximum file size: 100MB',
      'Text-based PDFs yield better results than scanned image PDFs.',
    ],
  },
  textbook: {
    id: 'textbook',
    title: 'Textbook Pages',
    description: 'Printed book pages and scanned chapters',
    icon: BookOpen,
    acceptedTypes: 'image/png, image/jpeg',
    maxFileSize: '20MB per image',
    multiple: true,
    processor: 'ocrProcessor',
    tips: [
      'Supported formats: PNG, JPG, JPEG',
      'Maximum file size: 20MB per image',
      'Ensure good lighting and avoid glare on glossy pages.',
      'You can upload multiple pages at once.',
    ],
  },
  handwritten: {
    id: 'handwritten',
    title: 'Handwritten Notes',
    description: 'Notebook photos and handwritten pages',
    icon: PenTool,
    acceptedTypes: 'image/png, image/jpeg',
    maxFileSize: '20MB per image',
    multiple: true,
    processor: 'ocrProcessor',
    tips: [
      'Supported formats: PNG, JPG, JPEG',
      'Maximum file size: 20MB per image',
      'Write clearly and ensure good contrast in your photos.',
      'You can upload multiple pages at once.',
    ],
  },
  text: {
    id: 'text',
    title: 'Paste Text',
    description: 'Already have lecture text? Paste it directly.',
    icon: Type,
    acceptedTypes: 'text/plain',
    maxFileSize: 'N/A',
    multiple: false,
    processor: 'textProcessor',
    tips: [
      'Simply paste your text into the editor.',
      'Maximum length: 50,000 characters.',
      'Great for copying and pasting from articles or existing notes.',
    ],
  },
};
