import { SupabaseClient } from '@supabase/supabase-js';
import { log } from '../utils/logger';

export interface NoteInsertInput {
  lectureId: string;
  content: string;
  generatedBy: string;
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled';
  version?: number;
  title?: string | null;
  sourceType?: string;
}

export async function insertNote(
  supabase: SupabaseClient,
  input: NoteInsertInput
): Promise<{ id: string }> {
  log.info('NotesRepo', 'Inserting notes row', {
    'Lecture ID': input.lectureId,
    'Status': input.status,
    'Generated by': input.generatedBy,
    'Content length': String(input.content.length),
  });

  const { data, error } = await supabase
    .from('notes')
    .insert({
      lecture_id: input.lectureId,
      title: input.title ?? 'Smart Notes',
      content: input.content,
      version: input.version ?? 1,
      source_type: input.sourceType ?? 'ai',
      generated_by: input.generatedBy,
      status: input.status,
    })
    .select('id')
    .single();

  if (error) {
    throw new Error(`Failed to insert note: ${error.message}`);
  }

  return data as { id: string };
}
